version: "3.8"
services:
  server:
    build: ./api
    container_name: "express_server"
    ports:
     - "8000:8000"
    volumes:
     - ./api:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
     - db
    environment:
     - DB_HOST=db  # Use the service name 'db' as the hostname
  client:
    build: ./client
    container_name: "client"
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
  db:
    build: ./db
    container_name: "db"
    ports:
     - "27017:27017"
    logging:
      driver: "none"
    command:  # This hides the mongodb outputs
     - '--logpath'
     - '/var/log/mongodb/mongod.log'